color0 #3f4a3b
color1 #ffb4ab
color2 #75de63
color3 #a4d395
color4 #9acbff
color5 #75de63
color6 #a4d395
color7 #dee5d7
color8 #899482
color9 #ffb4ab
color10 #75de63
color11 #a4d395
color12 #9acbff
color13 #75de63
color14 #a4d395
color15 #dee5d7

cursor                #dee5d7
cursor_text_color     #0f150d
background            #0f150d
foreground            #dee5d7
selection_foreground  #becab6
selection_background  #3f4a3b
active_border_color   #75de63
inactive_border_color #3f4a3b
url_color             #75de63

active_tab_foreground   #003a01
active_tab_background   #75de63
inactive_tab_foreground #becab6
inactive_tab_background #3f4a3b
cursor_trail_color      #becab6
